In [6]:
import pandas as pd
import numpy as np
df = pd.read_excel("C:\\Users\\Hitesh\\Downloads\\19CSE305_LabData_Set3.1.xlsx",'thyroid0387_UCI')
df

,Record ID,age,sex,on thyroxine,query on thyroxine,on antithyroid medication,sick,pregnant,thyroid surgery,I131 treatment,...,TT4 measured,TT4,T4U measured,T4U,FTI measured,FTI,TBG measured,TBG,referral source,Condition
0,840801013,29,F,f,f,f,f,f,f,f,...,f,?,f,?,f,?,f,?,other,NO CONDITION
1,840801014,29,F,f,f,f,f,f,f,f,...,t,128,f,?,f,?,f,?,other,NO CONDITION
2,840801042,41,F,f,f,f,f,f,f,f,...,f,?,f,?,f,?,t,11,other,NO CONDITION
3,840803046,36,F,f,f,f,f,f,f,f,...,f,?,f,?,f,?,t,26,other,NO CONDITION
4,840803047,32,F,f,f,f,f,f,f,f,...,f,?,f,?,f,?,t,36,other,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,841031002,41,F,f,f,f,f,f,f,f,...,t,148,t,1.44,t,103,f,?,STMW,NO CONDITION
996,841031010,41,F,f,f,f,f,f,f,f,...,t,9.7,t,1.46,t,6.6,f,?,other,F
997,841031030,20,F,f,f,f,f,t,f,f,...,f,?,f,?,f,?,t,30,other,NO CONDITION
998,841031031,20,F,f,f,f,f,f,f,f,...,t,201,t,0.84,t,240,f,?,SVI,AK
999,841031032,73,F,f,f,f,f,f,f,f,...,t,85,t,0.9,t,94,f,?,SVI,NO CONDITION

In [7]:



def identify_data_type(column):

    unique_values = column.unique()

    num_unique_values = len(unique_values)

 

    if num_unique_values == 2:

        return 'Binary (Nominal)'

    elif num_unique_values > 2 and num_unique_values <= 10:

        return 'Categorical (Nominal)'

    elif num_unique_values > 10:

        return 'Continuous'

 


for column in df.columns:

    data_type = identify_data_type(df[column])

    print(f' {column} ->  {data_type}')

 Record ID ->  Continuous
 age ->  Continuous
 sex ->  Categorical (Nominal)
 on thyroxine ->  Binary (Nominal)
 query on thyroxine ->  Binary (Nominal)
 on antithyroid medication ->  Binary (Nominal)
 sick ->  Binary (Nominal)
 pregnant ->  Binary (Nominal)
 thyroid surgery ->  Binary (Nominal)
 I131 treatment ->  Binary (Nominal)
 query hypothyroid ->  Binary (Nominal)
 query hyperthyroid ->  Binary (Nominal)
 lithium ->  None
 goitre ->  Binary (Nominal)
 tumor ->  Binary (Nominal)
 hypopituitary ->  Binary (Nominal)
 psych ->  Binary (Nominal)
 TSH measured ->  Binary (Nominal)
 TSH ->  Continuous
 T3 measured ->  Binary (Nominal)
 T3 ->  Continuous
 TT4 measured ->  Binary (Nominal)
 TT4 ->  Continuous
 T4U measured ->  Binary (Nominal)
 T4U ->  Continuous
 FTI measured ->  Binary (Nominal)
 FTI ->  Continuous
 TBG measured ->  Binary (Nominal)
 TBG ->  Continuous
 referral source ->  Categorical (Nominal)
 Condition ->  Continuous